services:
    _defaults:
        autoconfigure: true
        autowire: false
        public: false

    Terminal42\AutoRegistrationBundle\EventListener\RegistrationListener:
        arguments:
            - '@security.helper'
            - '@contao.security.frontend_user_provider'
            - '@database_connection'
